source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# syntax highlighting
antigen bundle zsh-users/zsh-syntax-highlighting
# history substring search
antigen bundle zsh-users/zsh-history-substring-search
# completions
antigen bundle zsh-users/zsh-completions
# autosuggestions
antigen bundle zsh-users/zsh-autosuggestions

# Load the theme.
antigen theme robbyrussell

# Tell Antigen that you're done.
antigen apply